#!/bin/bash

function setupenv()  {
 source /opt/ros/humble/setup.bash # configure ROS system install environment
 source ~/interbotix_ws/install/setup.bash # configure ROS workspace environment
}

function startup() {
 coproc STARTUP { # Launches this process in the same tty in parallel with current
  source /opt/ros/humble/setup.bash # configure ROS system install environment
  source ~/interbotix_ws/install/setup.bash # configure ROS workspace environment
   eval "ros2 launch aloha aloha_bringup.launch.py robot:=aloha_mobile >log.txt 2>&1"
  while true; do
	clear
        echo "Type Ctrl+C when done"
  done
}
}

function cleanup_safeshutdown() {
 export INTERBOTIX_ALOHA_IS_MOBILE=true
 echo "## safely shutting down robot ##"
 eval "python3 sleep.py -r" # safely shut the robot down 
}



startup
cd ~/interbotix_ws/src/aloha/scripts/i
sleep 20
eval "python3 teleop.py -r aloha_mobile"
trap cleanup_safeshutdown SIGINT


