#!/bin/bash

function setupenv()  {
 source /opt/ros/humble/setup.bash # configure ROS system install environment
 source ~/interbotix_ws/install/setup.bash # configure ROS workspace environment
}

function startup() {
 coproc STARTUP {
  source /opt/ros/humble/setup.bash # configure ROS system install environment
  source ~/interbotix_ws/install/setup.bash # configure ROS workspace environment
  while true; do 
   ros2 launch aloha aloha_bringup.launch.py robot:=aloha_mobile
  done
}
}

function cleanup_safeshutdown() {
 export INTERBOTIX_ALOHA_IS_MOBILE=true
 python3 sleep.py -r
}



startup
cd ~/interbotix_ws/src/aloha/scripts/
python3 teleop.py -r aloha_mobile
trap cleanup_safeshutdown SIGINT


